// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace SolIS4.STS
{
    [Table("SegSSOMAplicacion")]
    public partial class SegSSOMAplicacion
    {
        [Key]
        public int PK_eIdAplicacion { get; set; }
        public int FK_eIdGrupo { get; set; }
        public int eTipoSeguridad { get; set; }
        [Required]
        [StringLength(1)]
        public string cFlgTieneSobre { get; set; }
        [Required]
        [StringLength(250)]
        public string uNombreAplicacion { get; set; }
        [Required]
        [StringLength(250)]
        public string uDireccionAplicacion { get; set; }
        [Required]
        [StringLength(250)]
        public string uDireccionImagen { get; set; }
        [Required]
        [StringLength(1)]
        public string cFlgActivo { get; set; }
        [StringLength(1)]
        public string cFlgEliminado { get; set; }
        public int eIdSesionIngresa { get; set; }
        public int eIdSesionModifica { get; set; }
        [Required]
        [StringLength(1)]
        public string cFlgAutoregistro { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime fFechaActivacion { get; set; }
        [Required]
        [StringLength(1)]
        public string cBloqueoPermanente { get; set; }
        [Required]
        [StringLength(1)]
        public string cEsVisible { get; set; }
        public byte[] vImagenPreliminar { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime fFechaRegistro { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime fFechaActualizacion { get; set; }
    }
}